### PR TITLE
ci(kitchen): add Kitchen tests

### PR DESCRIPTION
**Pull request by n-rodriguez**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [x] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [x] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [x] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by myii** [comment]
Added to Taiga: https://tree.taiga.io/project/myii-saltstack-formulas/task/398.

@n-rodriguez Is there any particular order you'd like me to work through these (i.e. between this PR and https://github.com/saltstack-formulas/rng-tools-formula/issues/1)?

**Comment by n-rodriguez** [comment]
> @n-rodriguez Is there any particular order you'd like me to work through these

yes :) lynis first :+1:

**Comment by n-rodriguez** [comment]
@myii I think this one can be merged as is (if it's ok for you). in 5 minutes you'll have an other one with semantic-release which might need some work

**Comment by myii** [comment]
> @myii I think this one can be merged as is (if it's ok for you). in 5 minutes you'll have an other one with semantic-release which might need some work

@n-rodriguez Sure, go ahead.  I'll run the `ssf` against the new PR.

**Pull request merged**
